// SPDX-FileCopyrightText: Copyright (c) 2026 The Eclipse Foundation and pkcs11-go Authors
// SPDX-License-Identifier: MIT

// Command genconst translates the #define constants in the OASIS PKCS #11 type
// header (pkcs11t.h) into a Go source file of untyped constants.
//
// It is an independent implementation: it parses the OASIS header directly and
// applies the C-to-Go value rewrites required by the spec's value forms. Run it
// via `go generate ./cryptoki/...`; the produced file is committed to the repo.
//
// Usage:
//
//	go run ./cmd/genconst -header internal/headers/pkcs11t.h -out cryptoki/zconst.go -pkg cryptoki
package main

import (
	"bufio"
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"regexp"
	"strings"
)

// A define is one accepted "#define CK... value /* comment */" line.
type define struct {
	name    string // the C macro name, e.g. CKM_ML_KEM
	value   string // the Go-ready right-hand side
	comment string // trailing // comment text, without markers (may be empty)
}

// defineRE matches an object-like macro whose name begins with "CK". Group 1 is
// the name, group 2 is the raw value (up to a comment or end of line).
var defineRE = regexp.MustCompile(`^#define\s+(CK[0-9A-Z_a-z]*)\s+([^/]+?)\s*(?:/\*(.*)$)?$`)

// intSuffixRE strips C integer suffixes (U, L, UL, ULL, ...) from a numeric
// literal while leaving identifiers and operators untouched.
var intSuffixRE = regexp.MustCompile(`\b(0[xX][0-9A-Fa-f]+|[0-9]+)[uUlL]+\b`)

func main() {
	var headerPath, outPath, errPath, pkg string
	flag.StringVar(&headerPath, "header", "internal/headers/pkcs11t.h", "path to OASIS pkcs11t.h")
	flag.StringVar(&outPath, "out", "cryptoki/zconst.go", "path to the generated constants file")
	flag.StringVar(&errPath, "errout", "cryptoki/zerror.go", "path to the generated CKR name table")
	flag.StringVar(&pkg, "pkg", "cryptoki", "package name for the generated files")
	flag.Parse()

	defines, err := parse(headerPath)
	if err != nil {
		log.Fatalf("genconst: %v", err)
	}

	src, err := render(pkg, headerPath, defines)
	if err != nil {
		log.Fatalf("genconst: rendering %s: %v", outPath, err)
	}
	if err := os.WriteFile(outPath, src, 0o644); err != nil {
		log.Fatalf("genconst: writing %s: %v", outPath, err)
	}
	log.Printf("genconst: wrote %d constants to %s", len(defines), outPath)

	errSrc, n, err := renderErrors(pkg, headerPath, defines)
	if err != nil {
		log.Fatalf("genconst: rendering %s: %v", errPath, err)
	}
	if err := os.WriteFile(errPath, errSrc, 0o644); err != nil {
		log.Fatalf("genconst: writing %s: %v", errPath, err)
	}
	log.Printf("genconst: wrote %d CKR names to %s", n, errPath)
}

// parse reads every accepted CK* object-like macro from the header.
func parse(path string) ([]define, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	var out []define
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 64*1024), 1<<20)
	for sc.Scan() {
		m := defineRE.FindStringSubmatch(sc.Text())
		if m == nil {
			continue
		}
		out = append(out, define{
			name:    m[1],
			value:   translate(m[1], m[2]),
			comment: cleanComment(m[3]),
		})
	}
	return out, sc.Err()
}

// translate rewrites a C macro value into an equivalent Go expression.
func translate(name, raw string) string {
	v := strings.TrimSpace(raw)
	switch name {
	case "CK_TRUE":
		return "true"
	case "CK_FALSE":
		return "false"
	}
	// (~0UL) and friends denote an all-ones unsigned word; Go spells unary
	// bitwise complement as ^ and needs an explicit unsigned operand.
	if collapse(v) == "(~0)" {
		return "^uint(0)"
	}
	// Drop C integer suffixes wherever they appear (also inside parens).
	v = intSuffixRE.ReplaceAllString(v, "$1")
	// Tidy spacing around a bitwise-OR alias such as (CKF_ARRAY_ATTRIBUTE|0x211).
	if strings.HasPrefix(v, "(") && strings.Contains(v, "|") {
		v = strings.ReplaceAll(v, "|", " | ")
		v = strings.Join(strings.Fields(v), " ")
	}
	return v
}

// collapse removes whitespace and integer suffixes so value forms can be
// compared structurally (e.g. "( ~0UL )" -> "(~0)").
func collapse(v string) string {
	v = intSuffixRE.ReplaceAllString(v, "$1")
	return strings.Join(strings.Fields(v), "")
}

// cleanComment turns a raw trailing C comment body into a Go comment text.
func cleanComment(c string) string {
	c = strings.TrimSpace(strings.TrimSuffix(strings.TrimSpace(c), "*/"))
	return strings.TrimSpace(c)
}

// render emits gofmt'd source for the parsed defines, grouping by macro prefix.
func render(pkg, header string, defines []define) ([]byte, error) {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// SPDX-FileCopyrightText: Copyright (c) 2026 The Eclipse Foundation and pkcs11-go Authors\n")
	fmt.Fprintf(&b, "// SPDX-License-Identifier: MIT\n\n")
	fmt.Fprintf(&b, "// Code generated by \"go run ./cmd/genconst\"; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// Source: %s (OASIS PKCS #11 v3.2). See internal/headers/NOTICE.md.\n\n", header)
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	fmt.Fprintf(&b, "const (\n")

	prevPrefix := ""
	for _, d := range defines {
		if p := prefix(d.name); p != prevPrefix {
			if prevPrefix != "" {
				b.WriteByte('\n')
			}
			prevPrefix = p
		}
		if d.comment != "" {
			fmt.Fprintf(&b, "\t%s = %s // %s\n", d.name, d.value, d.comment)
		} else {
			fmt.Fprintf(&b, "\t%s = %s\n", d.name, d.value)
		}
	}
	fmt.Fprintf(&b, ")\n")

	return format.Source(b.Bytes())
}

// renderErrors emits a map from every CKR_ return value to its symbolic name,
// used by (cryptoki.Error).Error. It returns the source and the entry count.
func renderErrors(pkg, header string, defines []define) ([]byte, int, error) {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// SPDX-FileCopyrightText: Copyright (c) 2026 The Eclipse Foundation and pkcs11-go Authors\n")
	fmt.Fprintf(&b, "// SPDX-License-Identifier: MIT\n\n")
	fmt.Fprintf(&b, "// Code generated by \"go run ./cmd/genconst\"; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// Source: %s (OASIS PKCS #11 v3.2). See internal/headers/NOTICE.md.\n\n", header)
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	fmt.Fprintf(&b, "// ckrNames maps a Cryptoki CK_RV return value to its CKR_ symbol.\n")
	fmt.Fprintf(&b, "var ckrNames = map[Error]string{\n")

	n := 0
	for _, d := range defines {
		if !strings.HasPrefix(d.name, "CKR_") {
			continue
		}
		fmt.Fprintf(&b, "\t%s: %q,\n", d.name, d.name)
		n++
	}
	fmt.Fprintf(&b, "}\n")

	src, err := format.Source(b.Bytes())
	return src, n, err
}

// prefix returns the leading token of a macro name up to its first underscore,
// e.g. "CKM" for "CKM_ML_KEM". It is used only to insert blank-line grouping.
func prefix(name string) string {
	if i := strings.IndexByte(name, '_'); i >= 0 {
		return name[:i]
	}
	return name
}
